{
    "CVE-ID": "CVE-2018-20852",
    "NVD": {
        "Descriptions": "http.cookiejar.DefaultPolicy.domain_return_ok in Lib/http/cookiejar.py in Python before 3.7.3 does not correctly validate the domain: it can be tricked into sending existing cookies to the wrong server. An attacker may abuse this flaw by using a server with a hostname that has another valid hostname as a suffix (e.g., pythonicexample.com to steal cookies for example.com). When a program uses http.cookiejar.DefaultPolicy and tries to do an HTTP connection to an attacker-controlled server, existing cookies can be leaked to the attacker. This affects 2.x through 2.7.16, 3.x before 3.4.10, 3.5.x before 3.5.7, 3.6.x before 3.6.9, and 3.7.x before 3.7.3.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 5.3,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
        "Cvss3_VectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.0",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "2.7.16"
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.0.0",
                "VersionEndExcluding": "3.4.10",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.5.0",
                "VersionEndExcluding": "3.5.7",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.6.0",
                "VersionEndExcluding": "3.6.9",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.3",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.7.17rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.17rc1.rst"
            ],
            "BTS": {
                "bpo35121": {
                    "ID": "bpo35121",
                    "url": "https://bugs.python.org/issue35121",
                    "date": "2019-05-20-00-35-12",
                    "nonce": "RRi-HU",
                    "section": "Security"
                }
            }
        },
        "3.4.10": {
            "source": [
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.10.rst"
            ],
            "BTS": {
                "bpo35121": {
                    "ID": "bpo35121",
                    "url": "https://bugs.python.org/issue35121",
                    "date": "2018-12-30-14-35-19",
                    "nonce": "oWmiGU",
                    "section": "Library"
                }
            }
        },
        "3.5.7": {
            "source": [
                "https://github.com/python/cpython/blob/3.5/Misc/NEWS.d/3.5.7.rst"
            ],
            "BTS": {
                "bpo35121": {
                    "ID": "bpo35121",
                    "url": "https://bugs.python.org/issue35121",
                    "date": "2018-12-30-14-35-19",
                    "nonce": "oWmiGU",
                    "section": "Library"
                }
            }
        },
        "3.6.9rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.9rc1.rst"
            ],
            "BTS": {
                "bpo35121": {
                    "ID": "bpo35121",
                    "url": "https://bugs.python.org/issue35121",
                    "date": "2018-12-30-14-35-19",
                    "nonce": "oWmiGU",
                    "section": "Library"
                }
            }
        },
        "3.7.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.7.3rc1/Misc/NEWS.d/3.7.3rc1.rst"
            ],
            "BTS": {
                "bpo35121": {
                    "ID": "bpo35121",
                    "url": "https://bugs.python.org/issue35121",
                    "date": "2018-12-30-14-35-19",
                    "nonce": "oWmiGU",
                    "section": "Library"
                }
            }
        },
        "3.8.0a3": {
            "source": [
                "https://github.com/python/cpython/blob/main/Misc/NEWS.d/3.8.0a3.rst"
            ],
            "BTS": {
                "bpo35121": {
                    "ID": "bpo35121",
                    "url": "https://bugs.python.org/issue35121",
                    "date": "2018-12-30-14-35-19",
                    "nonce": "oWmiGU",
                    "section": "Library"
                }
            }
        }
    }
}