{
    "CVE-ID": "CVE-2019-10160",
    "NVD": {
        "Descriptions": "A security regression of CVE-2019-9636 was discovered in python since commit d537ab0ff9767ef024f26246899728f0116b1ec3 affecting versions 2.7, 3.5, 3.6, 3.7 and from v3.8.0a4 through v3.8.0b1, which still allows an attacker to exploit CVE-2019-9636 by abusing the user and password parts of a URL. When an application parses user-supplied URLs to store cookies, authentication credentials, or other kind of information, it is possible for an attacker to provide specially crafted URLs to make the application locate host-related information (e.g. cookies, authentication data) and send them to a different host than where it should, unlike if the URLs had been correctly parsed. The result of an attack may vary based on the application.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 9.8,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
        "Cvss3_VectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "CPEs": [
            {
                "URI": "cpe:/o:redhat:enterprise_linux:7.0",
                "FormattedString": "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python:3.7",
                "FormattedString": "cpe:2.3:a:python:python:3.7:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python:3.6.0",
                "FormattedString": "cpe:2.3:a:python:python:3.6.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python:3.5.0",
                "FormattedString": "cpe:2.3:a:python:python:3.5.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0a4",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "3.8.0b1"
            }
        ]
    },
    "Official": {
        "2.7.17rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.17rc1.rst"
            ],
            "BTS": {
                "bpo36742": {
                    "ID": "bpo36742",
                    "url": "https://bugs.python.org/issue36742",
                    "date": "2019-06-10-12-02-45",
                    "nonce": "UEdHXJ",
                    "section": "Library"
                }
            }
        },
        "3.5.8rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.5/Misc/NEWS.d/3.5.8rc1.rst"
            ],
            "BTS": {
                "bpo36742": {
                    "ID": "bpo36742",
                    "url": "https://bugs.python.org/issue36742",
                    "date": "2019-04-29-15-34-59",
                    "nonce": "QCUY0i",
                    "section": "Security"
                }
            }
        },
        "3.6.9rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.9rc1.rst"
            ],
            "BTS": {
                "bpo36742": {
                    "ID": "bpo36742",
                    "url": "https://bugs.python.org/issue36742",
                    "date": "2019-04-29-15-34-59",
                    "nonce": "QCUY0i",
                    "section": "Security"
                }
            }
        },
        "3.7.4rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.7.4/Misc/NEWS.d/3.7.4rc1.rst"
            ],
            "BTS": {
                "bpo36742": {
                    "ID": "bpo36742",
                    "url": "https://bugs.python.org/issue36742",
                    "date": "2019-04-29-15-34-59",
                    "nonce": "QCUY0i",
                    "section": "Security"
                }
            }
        },
        "3.8.0a4": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.0b1/Misc/NEWS.d/3.8.0a4.rst"
            ],
            "BTS": {
                "bpo36742": {
                    "ID": "bpo36742",
                    "url": "https://bugs.python.org/issue36742",
                    "date": "2019-04-29-15-34-59",
                    "nonce": "QCUY0i",
                    "section": "Security"
                }
            }
        }
    }
}