{
    "CVE-ID": "CVE-2022-48566",
    "NVD": {
        "Descriptions": "An issue was discovered in compare_digest in Lib/hmac.py in Python through 3.9.1. Constant-time-defeating optimisations were possible in the accumulator variable in hmac.compare_digest.",
        "Cvss2_BaseScore": 0,
        "Cvss3_BaseScore": 5.9,
        "Cvss2_VectorString": "",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "CPEs": [
            {
                "URI": "cpe:/o:debian:debian_linux:10.0",
                "FormattedString": "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "3.6.13",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.10",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0",
                "VersionEndExcluding": "3.8.7",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.9.0",
                "VersionEndExcluding": "3.9.1",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:netapp:converged_systems_advisor_agent:-",
                "FormattedString": "cpe:2.3:a:netapp:converged_systems_advisor_agent:-:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:netapp:active_iq_unified_manager:-::~~~windows~~",
                "FormattedString": "cpe:2.3:a:netapp:active_iq_unified_manager:-:*:*:*:*:windows:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:netapp:active_iq_unified_manager:-::~~~vmware_vsphere~~",
                "FormattedString": "cpe:2.3:a:netapp:active_iq_unified_manager:-:*:*:*:*:vmware_vsphere:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.6.13": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.13.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-28-06-06-47",
                    "nonce": "QGZClX",
                    "section": "Security"
                }
            }
        },
        "3.7.10": {
            "source": [
                "https://github.com/python/cpython/blob/3.7/Misc/NEWS.d/3.7.10.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-28-06-06-47",
                    "nonce": "QGZClX",
                    "section": "Security"
                }
            }
        },
        "3.8.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.7/Misc/NEWS.d/3.8.7rc1.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-28-06-06-47",
                    "nonce": "QGZClX",
                    "section": "Security"
                }
            }
        },
        "3.9.0b2": {
            "source": [
                "https://github.com/python/cpython/blob/v3.9.0b2/Misc/NEWS.d/3.9.0b2.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-27-18-04-52",
                    "nonce": "IzpNor",
                    "section": "Library"
                }
            }
        },
        "3.9.1rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.9.8/Misc/NEWS.d/3.9.1rc1.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-28-06-06-47",
                    "nonce": "QGZClX",
                    "section": "Security"
                }
            }
        },
        "3.10.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/3.12/Misc/NEWS.d/3.10.0a1.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-27-18-04-52",
                    "nonce": "IzpNor",
                    "section": "Library"
                }
            }
        },
        "3.10.0a3": {
            "source": [
                "https://github.com/python/cpython/blob/3.12/Misc/NEWS.d/3.10.0a3.rst"
            ],
            "BTS": {
                "bpo40791": {
                    "ID": "bpo40791",
                    "url": "https://bugs.python.org/issue40791",
                    "date": "2020-05-28-06-06-47",
                    "nonce": "QGZClX",
                    "section": "Security"
                }
            }
        }
    }
}