{
    "CVE-ID": "CVE-2017-18207",
    "NVD": {
        "Descriptions": "** DISPUTED ** The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \"need to be prepared to handle a wide variety of exceptions.\"",
        "Cvss2_BaseScore": 4.3,
        "Cvss3_BaseScore": 6.5,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "3.6.4"
            }
        ]
    },
    "Official": {
        "3.7.0b3": {
            "source": [
                "https://github.com/python/cpython/blob/v3.13.0a1/Misc/NEWS.d/3.7.0b3.rst"
            ],
            "BTS": {
                "bpo32056": {
                    "ID": "bpo32056",
                    "url": "https://bugs.python.org/issue32056",
                    "date": "2018-03-01-17-49-56",
                    "nonce": "IlpfgE",
                    "section": "Library"
                }
            }
        },
        "3.8.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.13.0a1/Misc/NEWS.d/3.8.0a1.rst"
            ],
            "BTS": {
                "bpo32056": {
                    "ID": "bpo32056",
                    "url": "https://bugs.python.org/issue32056",
                    "date": "2018-03-01-17-49-56",
                    "nonce": "IlpfgE",
                    "section": "Library"
                }
            }
        }
    }
}