{
    "CVE-ID": "CVE-2008-3144",
    "NVD": {
        "Descriptions": "Multiple integer overflows in the PyOS_vsnprintf function in Python/mysnprintf.c in Python 2.5.2 and earlier allow context-dependent attackers to cause a denial of service (memory corruption) or have unspecified other impact via crafted input to string formatting operations.  NOTE: the handling of certain integer values is also affected by related integer underflows and an off-by-one error.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 0,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "2.5.2"
            }
        ]
    },
    "Official": {
        "2.4.6c1": {
            "source": [
                "https://github.com/python/cpython/blob/2.4/Misc/NEWS"
            ],
            "BTS": {
                "bpo2588": {
                    "ID": "bpo2588",
                    "url": "https://bugs.python.org/issue2588",
                    "date": "",
                    "nonce": "",
                    "section": ""
                },
                "bpo2589": {
                    "ID": "bpo2589",
                    "url": "https://bugs.python.org/issue2589",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.5.3c1": {
            "source": [
                "https://github.com/python/cpython/blob/2.5/Misc/NEWS"
            ],
            "BTS": {
                "bpo2588": {
                    "ID": "bpo2588",
                    "url": "https://bugs.python.org/issue2588",
                    "date": "",
                    "nonce": "",
                    "section": ""
                },
                "bpo2589": {
                    "ID": "bpo2589",
                    "url": "https://bugs.python.org/issue2589",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}