{
    "CVE-ID": "CVE-2019-9740",
    "NVD": {
        "Descriptions": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
        "Cvss2_BaseScore": 4.3,
        "Cvss3_BaseScore": 6.1,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.0",
                "VersionEndExcluding": "2.7.17",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.5.0",
                "VersionEndExcluding": "3.5.8",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.6.0",
                "VersionEndExcluding": "3.6.9",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.4",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.7.17rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.17rc1.rst"
            ],
            "BTS": {
                "bpo30458": {
                    "ID": "bpo30458",
                    "url": "https://bugs.python.org/issue30458",
                    "date": "2019-04-10-08-53-30",
                    "nonce": "51E-DA",
                    "section": "Security"
                }
            }
        },
        "3.5.8rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.5/Misc/NEWS.d/3.5.8rc1.rst"
            ],
            "BTS": {
                "bpo30458": {
                    "ID": "bpo30458",
                    "url": "https://bugs.python.org/issue30458",
                    "date": "2019-04-10-08-53-30",
                    "nonce": "51E-DA",
                    "section": "Security"
                }
            }
        },
        "3.6.9rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.9rc1.rst"
            ],
            "BTS": {
                "bpo30458": {
                    "ID": "bpo30458",
                    "url": "https://bugs.python.org/issue30458",
                    "date": "2019-04-10-08-53-30",
                    "nonce": "51E-DA",
                    "section": "Security"
                }
            }
        },
        "3.7.4rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.7.4rc1/Misc/NEWS.d/3.7.4rc1.rst"
            ],
            "BTS": {
                "bpo30458": {
                    "ID": "bpo30458",
                    "url": "https://bugs.python.org/issue30458",
                    "date": "2019-04-10-08-53-30",
                    "nonce": "51E-DA",
                    "section": "Security"
                }
            }
        },
        "3.8.0a4": {
            "source": [
                "https://github.com/python/cpython/blob/main/Misc/NEWS.d/3.8.0a4.rst"
            ],
            "BTS": {
                "bpo30458": {
                    "ID": "bpo30458",
                    "url": "https://bugs.python.org/issue30458",
                    "date": "2019-04-10-08-53-30",
                    "nonce": "51E-DA",
                    "section": "Security"
                }
            }
        }
    }
}