{
    "CVE-ID": "CVE-2022-42919",
    "Official": {
        "3.11.0": {
            "source": [
                "https://github.com/python/cpython/blob/v3.11.0/Misc/NEWS.d/3.11.0.rst"
            ],
            "BTS": {
                "gh-issue97514": {
                    "ID": "gh-issue97514",
                    "url": "https://github.com/python/cpython/issues/97514",
                    "date": "2022-09-07-10-42-00",
                    "nonce": "Yggdsl",
                    "section": "Security"
                }
            }
        },
        "3.12.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.12.0a1/Misc/NEWS.d/3.12.0a1.rst"
            ],
            "BTS": {
                "gh-issue97514": {
                    "ID": "gh-issue97514",
                    "url": "https://github.com/python/cpython/issues/97514",
                    "date": "2022-09-07-10-42-00",
                    "nonce": "Yggdsl",
                    "section": "Security"
                }
            }
        }
    }
}